name: algad_infohub
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+3

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  bloc: ^8.1.0
  flutter_bloc: ^8.0.1
  firebase_core: ^2.2.0
  cloud_firestore: ^4.0.5
  google_fonts: ^3.0.1
  fluttertoast: ^8.0.9
  firebase_auth: ^4.1.2
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.10.0
  firebase_messaging: ^14.1.0
  flutter_linkify: ^6.0.0
  url_launcher: ^6.1.11
  flutter_native_splash: ^2.0.0
  dropdown_button2: ^2.1.4


flutter_icons:
  android: true
  ios: true
  image_path: "images/icon.png"


flutter_native_splash:
  color: "#2E8A99"
  image: images/logo.png
  android_12:
    image: images/logo.png
  android_gravity: center
  android: true
  ios: true



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: IconBroken
      fonts:
        - asset: images/icons.ttf


